---
name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    uses: hmt-aws-platform/cicd-workflows/.github/workflows/terraform-module-release.yml@main # main
    name: GitHub Release
    with:
      enable-cliff: true
